### ISSUE TITLE
Mistral all models always time out

### ISSUE THREAD

**Issue by AshleyTuring** [TheFireCo/genkit-plugins#130]
**Affected plugin(s)**

- [ ] Anthropic
- [ ] Azure OpenAI
- [ ] Cohere
- [ ] Convex
- [ ] Groq
- [x ] Mistral
- [ ] OpenAI

**Describe the bug**
When using 

      "mistral/open-mistral-7b", 
      "mistral/open-mixtral-8x7b",
      "mistral/open-mixtral-8x22b",
      "mistral/mistral-small",
      "mistral/mistral-medium",
      "mistral/mistral-large"

calling generate method we only get timeout messages

Request failed: The operation was aborted due to timeout
Request failed: The operation was aborted due to timeout
Request failed: The operation was aborted due to timeout
Request failed: The operation was aborted due to timeout
Request failed: The operation was aborted due to timeout
CATCH ERROR executeFlow:  DOMException [TimeoutError]: The operation was aborted due to timeout
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async MistralClient._request (file:/node_modules/@mistralai/mistralai/src/client.js:122:26)
    at async MistralClient.chat (file:/node_modules/@mistralai/mistralai/src/client.js:297:22)

**Plugin(s) version:**
 "@genkit-ai/ai": "^0.5.4",
        "@genkit-ai/dotprompt": "^0.5.4",
        "@genkit-ai/googleai": "^0.5.4",
        "@google-cloud/functions-framework": "^3.4.0",
        "axios": "^1.7.2",
        "firebase-admin": "^11.8.0",
        "firebase-functions": "^5.0.1",
        "genkit": "^0.5.4",
        "genkitx-anthropic": "^0.10.0",
        "genkitx-cohere": "^0.10.1",
        "genkitx-groq": "^0.10.0",
        "genkitx-mistral": "^0.10.0",
        "genkitx-ollamadynamic": "^0.5.99",
        "genkitx-openai": "^0.10.0",
        "handlebars": "^4.7.8",
        "openai": "^4.36.0",
        "zod": "^3.23.8"

**Comment by xavidop** [comment]
fixed here: https://github.com/TheFireCo/genkit-plugins/pull/256
