### ISSUE TITLE
[Cohere] Will throw an obscure error when parsing Tool definitions for complex input schemas

### ISSUE THREAD

**Issue by MichaelDoyle** [TheFireCo/genkit-plugins#75]
**Affected plugin(s)**

Cohere

**Describe the bug**
Cohere will throw an obscure error when parsing Tool definitions for complex input schemas. Cohere generally wants a "flat structure" (i.e. individual input params). However, there is support for `Dict` and `List`. At the very least, the error message should be more indicative of what is supported, and what is not.

```
Error: Unsupported Zod type: String
    at zodTypeToPythonType (/Users/michaeldoyle/repos/thirdparty/genkit-experiments/apps/model-garden/node_modules/.pnpm/genkitx-cohere@0.9.0_@aws-sdk+client-sso-oidc@3.588.0_@genkit-ai+ai@0.5.2_@genkit-ai+core@0.5.2/node_modules/genkitx-cohere/lib/command.js:203:11)
    at toCohereTool (/Users/michaeldoyle/repos/thirdparty/genkit-experiments/apps/model-garden/node_modules/.pnpm/genkitx-cohere@0.9.0_@aws-sdk+client-sso-oidc@3.588.0_@genkit-ai+ai@0.5.2_@genkit-ai+core@0.5.2/node_modules/genkitx-cohere/lib/command.js:210:13)
    at Array.map (<anonymous>)
    at toCohereRequestBody (/Users/michaeldoyle/repos/thirdparty/genkit-experiments/apps/model-garden/node_modules/.pnpm/genkitx-cohere@0.9.0_@aws-sdk+client-sso-oidc@3.588.0_@genkit-ai+ai@0.5.2_@genkit-ai+core@0.5.2/node_modules/genkitx-cohere/lib/command.js:425:55)
    at /Users/michaeldoyle/repos/thirdparty/genkit-experiments/apps/model-garden/node_modules/.pnpm/genkitx-cohere@0.9.0_@aws-sdk+client-sso-oidc@3.588.0_@genkit-ai+ai@0.5.2_@genkit-ai+core@0.5.2/node_modules/genkitx-cohere/lib/command.js:447:20
```

**To Reproduce**

_Example Tools Schema_
```typescript
defineTool(
  {
    name: 'getStockPrice',
    description: 'Get the price for the given stock ticker.',
    inputSchema: z.object({ symbol: z.string() }),
    outputSchema: z.any(),
  },
  async (input) => {
    // ...
  }
);
```

**Expected behavior**

**Plugin(s) version:**
0.9.0

**Genkit version:**
0.5.2

**Comment by Dabolus** [comment]
I can take a look at it. I'll also add some tests on that part since it's currently uncovered
